/* JS */ gapi.loaded_0(function(_){var window=this;
var vf,Na,Pa,ib,sb,qb,Fb,Mb,Te;_.b=function(a){return function(){return _.aa[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.aa=[];vf="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){a!=Array.prototype&&a!=Object.prototype&&(a[c]=f.value)};Na="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;Pa=function(){Pa=function(){};Na.Symbol||(Na.Symbol=ib)};
ib=function(){var a=0;return function(c){return"jscomp_symbol_"+(c||"")+a++}}();sb=function(){Pa();var a=Na.Symbol.iterator;a||(a=Na.Symbol.iterator=Na.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&vf(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return qb(this)}});sb=function(){}};qb=function(a){var c=0;return Fb(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};Fb=function(a){sb();a={next:a};a[Na.Symbol.iterator]=function(){return this};return a};
_.PK=function(a){sb();var c=a[window.Symbol.iterator];return c?c.call(a):qb(a)};_.jb="function"==typeof Object.create?Object.create:function(a){var c=function(){};c.prototype=a;return new c};if("function"==typeof Object.setPrototypeOf)Mb=Object.setPrototypeOf;else{var bc;a:{var cc={a:!0},wc={};try{wc.__proto__=cc;bc=wc.a;break a}catch(a){}bc=!1}Mb=bc?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}_.fe=Mb;
Te=function(a,c){if(c){var f=Na;a=a.split(".");for(var g=0;g<a.length-1;g++){var h=a[g];h in f||(f[h]={});f=f[h]}a=a[a.length-1];g=f[a];c=c(g);c!=g&&null!=c&&vf(f,a,{configurable:!0,writable:!0,value:c})}};Te("Array.prototype.find",function(a){return a?a:function(a,f){a:{var c=this;c instanceof String&&(c=String(c));for(var h=c.length,l=0;l<h;l++){var n=c[l];if(a.call(f,n,l,c)){a=n;break a}}a=void 0}return a}});var wf=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};
Te("WeakMap",function(a){function c(a){wf(a,g)||vf(a,g,{value:{}})}function f(a){var f=Object[a];f&&(Object[a]=function(a){c(a);return f(a)})}if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),f=Object.seal({}),g=new a([[c,2],[f,3]]);if(2!=g.get(c)||3!=g.get(f))return!1;g["delete"](c);g.set(f,4);return!g.has(c)&&4==g.get(f)}catch(v){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0,l=function(a){this.El=(h+=Math.random()+
1).toString();if(a){Pa();sb();a=_.PK(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};l.prototype.set=function(a,f){c(a);if(!wf(a,g))throw Error("ua`"+a);a[g][this.El]=f;return this};l.prototype.get=function(a){return wf(a,g)?a[g][this.El]:void 0};l.prototype.has=function(a){return wf(a,g)&&wf(a[g],this.El)};l.prototype["delete"]=function(a){return wf(a,g)&&wf(a[g],this.El)?delete a[g][this.El]:!1};return l});
Te("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),f=new a(_.PK([[c,"s"]]));if("s"!=f.get(c)||1!=f.size||f.get({x:4})||f.set({x:4},"t")!=f||2!=f.size)return!1;var g=f.entries(),h=g.next();if(h.done||h.value[0]!=c||"s"!=h.value[1])return!1;h=g.next();return h.done||4!=h.value[0].x||"t"!=h.value[1]||!g.next().done?!1:!0}catch(A){return!1}}())return a;Pa();sb();var c=new window.WeakMap,f=function(a){this.bw=
{};this.p4=l();this.size=0;if(a){a=_.PK(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};f.prototype.set=function(a,c){a=0===a?0:a;var f=g(this,a);f.list||(f.list=this.bw[f.id]=[]);f.DK?f.DK.value=c:(f.DK={next:this.p4,qia:this.p4.qia,head:this.p4,key:a,value:c},f.list.push(f.DK),this.p4.qia.next=f.DK,this.p4.qia=f.DK,this.size++);return this};f.prototype["delete"]=function(a){a=g(this,a);return a.DK&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.bw[a.id],a.DK.qia.next=
a.DK.next,a.DK.next.qia=a.DK.qia,a.DK.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.bw={};this.p4=this.p4.qia=l();this.size=0};f.prototype.has=function(a){return!!g(this,a).DK};f.prototype.get=function(a){return(a=g(this,a).DK)&&a.value};f.prototype.entries=function(){return h(this,function(a){return[a.key,a.value]})};f.prototype.keys=function(){return h(this,function(a){return a.key})};f.prototype.values=function(){return h(this,function(a){return a.value})};f.prototype.forEach=
function(a,c){for(var f=this.entries(),g;!(g=f.next()).done;)g=g.value,a.call(c,g[1],g[0],this)};f.prototype[window.Symbol.iterator]=f.prototype.entries;var g=function(a,f){var g=f&&typeof f;"object"==g||"function"==g?c.has(f)?g=c.get(f):(g=""+ ++n,c.set(f,g)):g="p_"+f;var h=a.bw[g];if(h&&wf(a.bw,g))for(a=0;a<h.length;a++){var l=h[a];if(f!==f&&l.key!==l.key||f===l.key)return{id:g,list:h,index:a,DK:l}}return{id:g,list:h,index:-1,DK:void 0}},h=function(a,c){var f=a.p4;return Fb(function(){if(f){for(;f.head!=
a.p4;)f=f.qia;for(;f.next!=f.head;)return f=f.next,{done:!1,value:c(f)};f=null}return{done:!0,value:void 0}})},l=function(){var a={};return a.qia=a.next=a.head=a},n=0;return f});
Te("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),g=new a(_.PK([c]));if(!g.has(c)||1!=g.size||g.add(c)!=g||1!=g.size||g.add({x:4})!=g||2!=g.size)return!1;var h=g.entries(),l=h.next();if(l.done||l.value[0]!=c||l.value[1]!=c)return!1;l=h.next();return l.done||l.value[0]==c||4!=l.value[0].x||l.value[1]!=l.value[0]?!1:h.next().done}catch(n){return!1}}())return a;Pa();sb();var c=function(a){this.Ka=
new window.Map;if(a){a=_.PK(a);for(var c;!(c=a.next()).done;)this.add(c.value)}this.size=this.Ka.size};c.prototype.add=function(a){a=0===a?0:a;this.Ka.set(a,a);this.size=this.Ka.size;return this};c.prototype["delete"]=function(a){a=this.Ka["delete"](a);this.size=this.Ka.size;return a};c.prototype.clear=function(){this.Ka.clear();this.size=0};c.prototype.has=function(a){return this.Ka.has(a)};c.prototype.entries=function(){return this.Ka.entries()};c.prototype.values=function(){return this.Ka.values()};
c.prototype.keys=c.prototype.values;c.prototype[window.Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(a,c){var f=this;this.Ka.forEach(function(g){return a.call(c,g,g,f)})};return c});Te("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!(0,window.isNaN)(a)&&window.Infinity!==a&&-window.Infinity!==a}});Te("Object.is",function(a){return a?a:function(a,f){return a===f?0!==a||1/a===1/f:a!==a&&f!==f}});_.na=_.na||{};_.D=this;
_.kf=function(a){return void 0!==a};_.fa=function(a){return"string"==typeof a};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var f=Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.ea=function(a){return"array"==_.da(a)};_.oa="closure_uid_"+(1E9*Math.random()>>>0);_.pa=Date.now||function(){return+new Date};_.Mu=function(a,c){a=a.split(".");var f=_.D;a[0]in f||"undefined"==typeof f.execScript||f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&_.kf(c)?f[g]=c:f=f[g]&&f[g]!==Object.prototype[g]?f[g]:f[g]={}};
_.J=function(a,c){function f(){}f.prototype=c.prototype;a.T=c.prototype;a.prototype=new f;a.prototype.constructor=a;a.yc=function(a,f,l){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return c.prototype[f].apply(a,g)}};
_.L=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
blogger:{url:":socialhost:/:session_prefix:_/widget/render/blogger?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},appfinder:{url:"https://gsuite.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},
"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});
var pe,ia,la;_.qe=function(a){return"number"==typeof a};_.gh=function(){};_.re=function(a){var c=_.da(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.vd=function(a){return"function"==_.da(a)};_.Vg=function(a){var c=typeof a;return"object"==c&&null!=a||"function"==c};pe=0;_.oe=function(a){return a[_.oa]||(a[_.oa]=++pe)};ia=function(a,c,f){return a.call.apply(a.bind,arguments)};
la=function(a,c,f){if(!a)throw Error();if(2<arguments.length){var g=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.H=function(a,c,f){_.H=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:la;return _.H.apply(null,arguments)};
_.we=Array.prototype.indexOf?function(a,c){return Array.prototype.indexOf.call(a,c,void 0)}:function(a,c){if(_.fa(a))return _.fa(c)&&1==c.length?a.indexOf(c,0):-1;for(var f=0;f<a.length;f++)if(f in a&&a[f]===c)return f;return-1};_.Wf=Array.prototype.lastIndexOf?function(a,c){return Array.prototype.lastIndexOf.call(a,c,a.length-1)}:function(a,c){var f=a.length-1;0>f&&(f=Math.max(0,a.length+f));if(_.fa(a))return _.fa(c)&&1==c.length?a.lastIndexOf(c,f):-1;for(;0<=f;f--)if(f in a&&a[f]===c)return f;return-1};
_.Be=Array.prototype.forEach?function(a,c,f){Array.prototype.forEach.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=_.fa(a)?a.split(""):a,l=0;l<g;l++)l in h&&c.call(f,h[l],l,a)};_.Ce=Array.prototype.filter?function(a,c){return Array.prototype.filter.call(a,c,void 0)}:function(a,c){for(var f=a.length,g=[],h=0,l=_.fa(a)?a.split(""):a,n=0;n<f;n++)if(n in l){var q=l[n];c.call(void 0,q,n,a)&&(g[h++]=q)}return g};
_.De=Array.prototype.map?function(a,c){return Array.prototype.map.call(a,c,void 0)}:function(a,c){for(var f=a.length,g=Array(f),h=_.fa(a)?a.split(""):a,l=0;l<f;l++)l in h&&(g[l]=c.call(void 0,h[l],l,a));return g};_.Ee=Array.prototype.some?function(a,c,f){return Array.prototype.some.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=_.fa(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&c.call(f,h[l],l,a))return!0;return!1}; _.Fe=Array.prototype.every?function(a,c,f){return Array.prototype.every.call(a,c,f)}:function(a,c,f){for(var g=a.length,h=_.fa(a)?a.split(""):a,l=0;l<g;l++)if(l in h&&!c.call(f,h[l],l,a))return!1;return!0};_.ve=function(a,c){return 0<=(0,_.we)(a,c)};
var lk;_.Ge=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};_.Gf=String.prototype.repeat?function(a,c){return a.repeat(c)}:function(a,c){return Array(c+1).join(a)};
_.rk=function(a,c){var f=0;a=(0,_.Ge)(String(a)).split(".");c=(0,_.Ge)(String(c)).split(".");for(var g=Math.max(a.length,c.length),h=0;0==f&&h<g;h++){var l=a[h]||"",n=c[h]||"";do{l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];n=/(\d*)(\D*)(.*)/.exec(n)||["","","",""];if(0==l[0].length&&0==n[0].length)break;f=lk(0==l[1].length?0:(0,window.parseInt)(l[1],10),0==n[1].length?0:(0,window.parseInt)(n[1],10))||lk(0==l[2].length,0==n[2].length)||lk(l[2],n[2]);l=l[3];n=n[3]}while(0==f)}return f}; lk=function(a,c){return a<c?-1:a>c?1:0};_.ne=2147483648*Math.random()|0;
a:{var Lc=_.D.navigator;if(Lc){var wd=Lc.userAgent;if(wd){_.We=wd;break a}}_.We=""}_.pf=function(a){return-1!=_.We.indexOf(a)};var tf;_.qf=function(a,c,f){for(var g in a)c.call(f,a[g],g,a)};tf="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.sf=function(a,c){for(var f,g,h=1;h<arguments.length;h++){g=arguments[h];for(f in g)a[f]=g[f];for(var l=0;l<tf.length;l++)f=tf[l],Object.prototype.hasOwnProperty.call(g,f)&&(a[f]=g[f])}};
_.$e=function(){return _.pf("Opera")};_.B=function(){return _.pf("Trident")||_.pf("MSIE")};_.ye=function(){return _.pf("Android")};_.mZ=function(){return _.pf("iPhone")&&!_.pf("iPod")&&!_.pf("iPad")};_.wk=function(){return _.mZ()||_.pf("iPad")||_.pf("iPod")};var lh=function(a){lh[" "](a);return a},Oe;lh[" "]=_.gh;_.Eo=function(a,c){try{return lh(a[c]),!0}catch(f){}return!1};Oe=function(a,c){var f=Zk;return Object.prototype.hasOwnProperty.call(f,a)?f[a]:f[a]=c(a)};var Pe,Ed,Zk,Xg;_.cf=_.$e();_.W=_.B();_.yk=_.pf("Edge");_.Vi=_.yk||_.W;_.df=_.pf("Gecko")&&!(-1!=_.We.toLowerCase().indexOf("webkit")&&!_.pf("Edge"))&&!(_.pf("Trident")||_.pf("MSIE"))&&!_.pf("Edge");_.ef=-1!=_.We.toLowerCase().indexOf("webkit")&&!_.pf("Edge");_.ff=_.ef&&_.pf("Mobile");_.Gg=_.pf("Macintosh");_.Im=_.pf("Windows");_.Jg=_.pf("Linux")||_.pf("CrOS");_.kO=_.ye();_.yO=_.mZ();_.WP=_.pf("iPad");_.XQ=_.pf("iPod");_.DU=_.wk();Pe=function(){var a=_.D.document;return a?a.documentMode:void 0};
a:{var Nd="",Bf=function(){var a=_.We;if(_.df)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.yk)return/Edge\/([\d\.]+)/.exec(a);if(_.W)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.ef)return/WebKit\/(\S+)/.exec(a);if(_.cf)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Bf&&(Nd=Bf?Bf[1]:"");if(_.W){var Vf=Pe();if(null!=Vf&&Vf>(0,window.parseFloat)(Nd)){Ed=String(Vf);break a}}Ed=Nd}_.Se=Ed;Zk={};_.sl=function(a){return Oe(a,function(){return 0<=_.rk(_.Se,a)})};_.gq=function(a){return Number(_.Ue)>=a}; var Mh=_.D.document;Xg=Mh&&_.W?Pe()||("CSS1Compat"==Mh.compatMode?(0,window.parseInt)(_.Se,10):5):void 0;_.Ue=Xg;

var Af,Ye,Xe,Re,Me,Le,Ze,Ke;_.d=function(a,c){return _.aa[a]=c};_.bj=function(a){return Array.prototype.concat.apply([],arguments)};_.ze=function(a){var c=a.length;if(0<c){for(var f=Array(c),g=0;g<c;g++)f[g]=a[g];return f}return[]};_.jd=function(a,c){return 0==a.lastIndexOf(c,0)};Ye=/&/g;Xe=/</g;Re=/>/g;Me=/"/g;Le=/'/g;Ze=/\x00/g;Ke=/[\x00&<>"']/;
_.He=function(a){if(!Ke.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ye,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Xe,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Re,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Me,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Le,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ze,"&#0;"));return a};_.Cg=function(a){return String(a).replace(/\-([a-z])/g,function(a,f){return f.toUpperCase()})};_.hi=function(a,c){for(var f in a)if(a[f]==c)return!0;return!1};
var Nf,Xo;Nf=!_.W||_.gq(9);Xo=!_.df&&!_.W||_.W&&_.gq(9)||_.df&&_.sl("1.9.1");_.ag=_.W&&!_.sl("9");_.Zn=_.W||_.cf||_.ef;_.qm=_.W&&!_.gq(9);var Us;_.ou=function(){this.C5="";this.sda=Us};_.ou.prototype.nK=!0;_.ou.prototype.cR=function(){return this.C5};_.ou.prototype.toString=function(){return"Const{"+this.C5+"}"};_.ru=function(a){return a instanceof _.ou&&a.constructor===_.ou&&a.sda===Us?a.C5:"type_error:Const"};Us={};_.Kh=function(a){var c=new _.ou;c.C5=a;return c};_.Kh("");
var WD;_.qE=function(){this.N8="";this.tda=WD};_.qE.prototype.nK=!0;_.qE.prototype.cR=function(){return this.N8};_.qE.prototype.mK=!0;_.qE.prototype.Im=function(){return 1};_.wx=function(a){if(a instanceof _.qE&&a.constructor===_.qE&&a.tda===WD)return a.N8;_.da(a);return"type_error:TrustedResourceUrl"};_.nq=function(a){return _.l_(_.ru(a))};WD={};_.l_=function(a){var c=new _.qE;c.N8=a;return c};
var vU,pu,hg;_.su=function(){this.d_="";this.rda=pu};_.su.prototype.nK=!0;_.su.prototype.cR=function(){return this.d_};_.su.prototype.mK=!0;_.su.prototype.Im=function(){return 1};_.Ls=function(a){if(a instanceof _.su&&a.constructor===_.su&&a.rda===pu)return a.d_;_.da(a);return"type_error:SafeUrl"};vU=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;_.jw=function(a){if(a instanceof _.su)return a;a=a.nK?a.cR():String(a);vU.test(a)||(a="about:invalid#zClosurez");return hg(a)}; _.Lm=function(a){if(a instanceof _.su)return a;a=a.nK?a.cR():String(a);vU.test(a)||(a="about:invalid#zClosurez");return hg(a)};pu={};hg=function(a){var c=new _.su;c.d_=a;return c};hg("about:blank");
_.pm=function(){this.M8="";this.qda=_.nm};_.pm.prototype.nK=!0;_.nm={};_.pm.prototype.cR=function(){return this.M8};_.pm.prototype.XY=function(a){this.M8=a;return this};_.rm=(new _.pm).XY("");_.xm=function(){this.L8="";this.pda=_.Bl};_.xm.prototype.nK=!0;_.Bl={};_.iM=function(a){a=_.ru(a);return 0===a.length?ns:(new _.xm).XY(a)};_.xm.prototype.cR=function(){return this.L8};_.xm.prototype.XY=function(a){this.L8=a;return this};var ns=(new _.xm).XY("");
var XM;_.NG=function(){this.d_="";this.oda=XM;this.Z$=null};_.NG.prototype.mK=!0;_.NG.prototype.Im=function(){return this.Z$};_.NG.prototype.nK=!0;_.NG.prototype.cR=function(){return this.d_};_.OG=function(a){if(a instanceof _.NG&&a.constructor===_.NG&&a.oda===XM)return a.d_;_.da(a);return"type_error:SafeHtml"};XM={};_.uf=function(a,c){return(new _.NG).XY(a,c)};_.NG.prototype.XY=function(a,c){this.d_=a;this.Z$=c;return this};_.uf("<!DOCTYPE html>",0);_.RG=_.uf("",0);_.Pp=_.uf("<br>",0);
_.ht=function(a,c){c=c instanceof _.su?c:_.Lm(c);a.href=_.Ls(c)};var Ff,Of,pg;_.xf=function(a){return a?new _.yf(_.zf(a)):Af||(Af=new _.yf)};_.Ci=function(a,c){return _.fa(c)?a.getElementById(c):c};
_.Cf=function(a,c,f,g){a=g||a;c=c&&"*"!=c?String(c).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(c||f))return a.querySelectorAll(c+(f?"."+f:""));if(f&&a.getElementsByClassName){a=a.getElementsByClassName(f);if(c){g={};for(var h=0,l=0,n;n=a[l];l++)c==n.nodeName&&(g[h++]=n);g.length=h;return g}return a}a=a.getElementsByTagName(c||"*");if(f){g={};for(l=h=0;n=a[l];l++)c=n.className,"function"==typeof c.split&&_.ve(c.split(/\s+/),f)&&(g[h++]=n);g.length=h;return g}return a};
_.Ef=function(a,c){_.qf(c,function(c,g){c&&c.nK&&(c=c.cR());"style"==g?a.style.cssText=c:"class"==g?a.className=c:"for"==g?a.htmlFor=c:Ff.hasOwnProperty(g)?a.setAttribute(Ff[g],c):_.jd(g,"aria-")||_.jd(g,"data-")?a.setAttribute(g,c):a[g]=c})};Ff={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.jg=function(a){return a?a.parentWindow||a.defaultView:window};_.Mf=function(a,c){var f=String(c[0]),g=c[1];if(!Nf&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',_.He(g.name),'"');if(g.type){f.push(' type="',_.He(g.type),'"');var h={};_.sf(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=a.createElement(f);g&&(_.fa(g)?f.className=g:_.ea(g)?f.className=g.join(" "):_.Ef(f,g));2<c.length&&Of(a,f,c,2);return f};
Of=function(a,c,f,g){function h(f){f&&c.appendChild(_.fa(f)?a.createTextNode(f):f)}for(;g<f.length;g++){var l=f[g];!_.re(l)||_.Vg(l)&&0<l.nodeType?h(l):(0,_.Be)(pg(l)?_.ze(l):l,h)}};_.Br=function(a){return window.document.createElement(String(a))};_.Qx=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.xp=function(a,c){Of(_.zf(a),a,arguments,1)};_.Qf=function(a){for(var c;c=a.firstChild;)a.removeChild(c)};_.Rf=function(a,c){c.parentNode&&c.parentNode.insertBefore(a,c)};_.Tf=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.Uf=function(a){var c,f=a.parentNode;if(f&&11!=f.nodeType){if(a.removeNode)return a.removeNode(!1);for(;c=a.firstChild;)f.insertBefore(c,a);return _.Tf(a)}};
_.SO=function(a){return Xo&&void 0!=a.children?a.children:(0,_.Ce)(a.childNodes,function(a){return 1==a.nodeType})};_.iz=function(a){return _.Vg(a)&&1==a.nodeType};_.Yf=function(a,c){if(!a||!c)return!1;if(a.contains&&1==c.nodeType)return a==c||a.contains(c);if("undefined"!=typeof a.compareDocumentPosition)return a==c||!!(a.compareDocumentPosition(c)&16);for(;c&&a!=c;)c=c.parentNode;return c==a};_.zf=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.Zf=function(a,c){if("textContent"in a)a.textContent=c;else if(3==a.nodeType)a.data=String(c);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(c)}else _.Qf(a),a.appendChild(_.zf(a).createTextNode(String(c)))};pg=function(a){if(a&&"number"==typeof a.length){if(_.Vg(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.vd(a))return"function"==typeof a.item}return!1};
_.yf=function(a){this.wc=a||_.D.document||window.document};_.k=_.yf.prototype;_.k.Ha=_.xf;_.k.v5=_.b(0);_.k.Wb=function(){return this.wc};_.k.Kb=function(a){return _.Ci(this.wc,a)};_.k.getElementsByTagName=function(a,c){return(c||this.wc).getElementsByTagName(String(a))};_.k.R=function(a,c,f){return _.Mf(this.wc,arguments)};_.k.createElement=function(a){return this.wc.createElement(String(a))};_.k.createTextNode=function(a){return this.wc.createTextNode(String(a))};
_.k.Aa=function(){var a=this.wc;return a.parentWindow||a.defaultView};_.k.appendChild=function(a,c){a.appendChild(c)};_.k.append=_.xp;_.k.canHaveChildren=_.Qx;_.k.u0=_.Qf;_.k.Sl=_.Rf;_.k.removeNode=_.Tf;_.k.Hp=_.Uf;_.k.NR=_.SO;_.k.isElement=_.iz;_.k.contains=_.Yf;_.k.kJ=_.b(1);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.ta=window;_.ua=window.document;_.Ha=_.ta.location;_.Ia=/\[native code\]/;_.Ka=function(a,c,f){return a[c]=a[c]||f};_.r=function(){var a;if((a=Object.create)&&_.Ia.test(a))a=a(null);else{a={};for(var c in a)a[c]=void 0}return a};_.Qa=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};_.Sl=function(a,c){a=a||{};for(var f in a)_.Qa(a,f)&&(c[f]=a[f])};_.Ua=_.Ka(_.ta,"gapi",{});
_.e=function(a,c,f){var g=new RegExp("([#].*&|[#])"+c+"=([^&#]*)","g");c=new RegExp("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.Xa=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);
_.Za=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.lc=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.La=function(a,c,f){_.ra(a,c,f,"add","at")};_.ra=function(a,c,f,g,h){if(a[g+"EventListener"])a[g+"EventListener"](c,f,!1);else if(a[h+"tachEvent"])a[h+"tachEvent"]("on"+c,f)};_.bb=_.Ka(_.ta,"___jsl",_.r());_.Ka(_.bb,"I",0);_.Ka(_.bb,"hel",10);var ya,za,Aa,Ba,Da,Ea,Hg;ya=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};za=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};Aa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
Ba=function(a,c,f){if(c&&"object"===typeof c)for(var g in c)!Object.prototype.hasOwnProperty.call(c,g)||f&&"___goc"===g&&"undefined"===typeof c[g]||(a[g]&&c[g]&&"object"===typeof a[g]&&"object"===typeof c[g]&&!Aa(a[g])&&!Aa(c[g])?Ba(a[g],c[g]):c[g]&&"object"===typeof c[g]?(a[g]=Aa(c[g])?[]:{},Ba(a[g],c[g])):a[g]=c[g])};
Da=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);try{var c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new Function("return ("+a+"\n)"))()}catch(f){}if("object"===typeof c)return c;try{c=(new Function("return ({"+a+"\n})"))()}catch(f){}return"object"===typeof c?c:{}}};
Ea=function(a,c){var f={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(f=a.pop());Ba(f,c);a.push(f)};
Hg=function(a){za(!0);var c=window.___gcfg,f=ya("cu"),g=window.___gu;c&&c!==g&&(Ea(f,c),window.___gu=c);c=ya("cu");var h=window.document.scripts||window.document.getElementsByTagName("script")||[];g=[];var l=[];l.push.apply(l,ya("us"));for(var n=0;n<h.length;++n)for(var q=h[n],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&0<h.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||(g[h].setAttribute("gapi_processed",!0),
(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=void 0,(l=Da(l))&&c.push(l));a&&Ea(f,a);g=ya("cd");a=0;for(c=g.length;a<c;++a)Ba(za(),g[a],!0);g=ya("ci");a=0;for(c=g.length;a<c;++a)Ba(za(),g[a],!0);a=0;for(c=f.length;a<c;++a)Ba(za(),f[a],!0)};_.P=function(a,c){var f=za();if(!a)return f;a=a.split("/");for(var g=0,h=a.length;f&&"object"===typeof f&&g<h;++g)f=f[a[g]];return g===a.length&&void 0!==f?f:c}; _.Fa=function(a,c){var f;if("string"===typeof a){var g=f={};a=a.split("/");for(var h=0,l=a.length;h<l-1;++h){var n={};g=g[a[h]]=n}g[a[h]]=c}else f=a;Hg(f)};
var Ga=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Ka(_.bb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};Ga&&Ga();Hg();_.Mu("gapi.config.get",_.P);_.Mu("gapi.config.update",_.Fa);
_.Gl=function(a,c){for(var f=1;f<arguments.length;f++){var g=arguments[f];if(_.re(g)){var h=a.length||0,l=g.length||0;a.length=h+l;for(var n=0;n<l;n++)a[h+n]=g[n]}else a.push(g)}};_.im=function(a){return/^[\s\xa0]*$/.test(a)};_.Df=function(a,c){var f=c||window.document;if(f.getElementsByClassName)a=f.getElementsByClassName(a)[0];else{f=window.document;var g=c||f;a=g.querySelectorAll&&g.querySelector&&a?g.querySelector(a?"."+a:""):_.Cf(f,"*",a,c)[0]||null}return a||null};

(function(){function a(a,c){if(!(a<f)&&g)if(2===a&&g.warn)g.warn(c);else if(3===a&&g.error)try{g.error(c)}catch(n){}else g.log&&g.log(c)}var c=function(c){a(1,c)};_.Lb=function(c){a(2,c)};_.sa=function(c){a(3,c)};_.Fc=function(){};c.INFO=1;c.WARNING=2;c.NONE=4;var f=1,g=window.console?window.console:window.opera?window.opera.postError:void 0;return c})();

_.R=_.R||{};
_.R=_.R||{};(function(){var a=[];_.R.du=function(c){a.push(c)};_.R.XX=function(){for(var c=0,f=a.length;c<f;++c)a[c]()}})();
_.R=_.R||{};
(function(){var a=null;_.R.Qc=function(c){var f="undefined"===typeof c;if(null!==a&&f)return a;var g={};c=c||window.location.href;var h=c.indexOf("?"),l=c.indexOf("#");c=(-1===l?c.substr(h+1):[c.substr(h+1,l-h-1),"&",c.substr(l+1)].join("")).split("&");h=window.decodeURIComponent?window.decodeURIComponent:window.unescape;l=0;for(var n=c.length;l<n;++l){var q=c[l].indexOf("=");if(-1!==q){var t=c[l].substring(0,q);q=c[l].substring(q+1);q=q.replace(/\+/g," ");try{g[t]=h(q)}catch(v){}}}f&&(a=g);return g}; _.R.Qc()})();
_.Mu("gadgets.util.getUrlParameters",_.R.Qc);
var Kd;Kd=window.console;_.kd=function(a){Kd&&Kd.log&&Kd.log(a)};_.nH=function(a){Kd&&(Kd.error?Kd.error(a):Kd.log&&Kd.log(a))};_.ke=function(){};
_.Pb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.Fa(a());return{register:function(a,f,g){g&&g(_.P())},get:function(a){return _.P(a)},update:function(a,f){if(f)throw"Config replacement is not supported";_.Fa(a)},kc:function(){}}}();
_.Mu("gadgets.config.register",_.Pb.register);_.Mu("gadgets.config.get",_.Pb.get);_.Mu("gadgets.config.init",_.Pb.kc);_.Mu("gadgets.config.update",_.Pb.update);
var Qe,af,aj,yu,Zi,mk,Iu,vl,xl,zD,jq,qt,Is,Js,AF,aH,DH,QL,SL,bN,aR,CR,DR,ES,KT,xU,pV,vW,KX,me,SE,qy,QA;aj=void 0;yu=function(a){try{return _.D.JSON.parse.call(_.D.JSON,a)}catch(c){return!1}};Zi=function(a){return Object.prototype.toString.call(a)};mk=Zi(0);Iu=Zi(new Date(0));vl=Zi(!0);xl=Zi("");zD=Zi({});jq=Zi([]);
qt=function(a,c){if(c)for(var f=0,g=c.length;f<g;++f)if(a===c[f])throw new TypeError("Converting circular structure to JSON");g=typeof a;if("undefined"!==g){f=Array.prototype.slice.call(c||[],0);f[f.length]=a;c=[];var h=Zi(a);if(null!=a&&"function"===typeof a.toJSON&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(h!==jq||a.constructor!==Array&&a.constructor!==Object)&&(h!==zD||a.constructor!==Array&&a.constructor!==Object)&&h!==xl&&h!==mk&&h!==vl&&h!==Iu))return qt(a.toJSON.call(a),f);if(null==
a)c[c.length]="null";else if(h===mk)a=Number(a),(0,window.isNaN)(a)||(0,window.isNaN)(a-a)?a="null":-0===a&&0>1/a&&(a="-0"),c[c.length]=String(a);else if(h===vl)c[c.length]=String(!!Number(a));else{if(h===Iu)return qt(a.toISOString.call(a),f);if(h===jq&&Zi(a.length)===mk){c[c.length]="[";var l=0;for(g=Number(a.length)>>0;l<g;++l)l&&(c[c.length]=","),c[c.length]=qt(a[l],f)||"null";c[c.length]="]"}else if(h==xl&&Zi(a.length)===mk){c[c.length]='"';l=0;for(f=Number(a.length)>>0;l<f;++l)g=String.prototype.charAt.call(a,
l),h=String.prototype.charCodeAt.call(a,l),c[c.length]="\b"===g?"\\b":"\f"===g?"\\f":"\n"===g?"\\n":"\r"===g?"\\r":"\t"===g?"\\t":"\\"===g||'"'===g?"\\"+g:31>=h?"\\u"+(h+65536).toString(16).substr(1):32<=h&&65535>=h?g:"\ufffd";c[c.length]='"'}else if("object"===g){c[c.length]="{";g=0;for(l in a)Object.prototype.hasOwnProperty.call(a,l)&&(h=qt(a[l],f),void 0!==h&&(g++&&(c[c.length]=","),c[c.length]=qt(l),c[c.length]=":",c[c.length]=h));c[c.length]="}"}else return}return c.join("")}};Is=/[\0-\x07\x0b\x0e-\x1f]/;
Js=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;AF=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;aH=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;DH=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;QL=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;SL=/[ \t\n\r]+/g;bN=/[^"]:/;aR=/""/g;CR=/true|false|null/g;DR=/00/;ES=/[\{]([^0\}]|0[^:])/;KT=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;xU=/[^\[,:][\[\{]/;pV=/^(\{|\}|\[|\]|,|:|0)+/;vW=/\u2028/g;
KX=/\u2029/g;
me=function(a){a=String(a);if(Is.test(a)||Js.test(a)||AF.test(a)||aH.test(a))return!1;var c=a.replace(DH,'""');c=c.replace(QL,"0");c=c.replace(SL,"");if(bN.test(c))return!1;c=c.replace(aR,"0");c=c.replace(CR,"0");if(DR.test(c)||ES.test(c)||KT.test(c)||xU.test(c)||!c||(c=c.replace(pV,"")))return!1;a=a.replace(vW,"\\u2028").replace(KX,"\\u2029");c=void 0;try{c=aj?[yu(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(f){return!1}return c&&1===
c.length?c[0]:!1};SE=function(){var a=((_.D.document||{}).scripts||[]).length;if((void 0===Qe||void 0===aj||af!==a)&&-1!==af){Qe=aj=!1;af=-1;try{try{aj=!!_.D.JSON&&'{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'===_.D.JSON.stringify.call(_.D.JSON,{a:[3,!0,new Date(0)],c:function(){}})&&!0===yu("true")&&3===yu('[{"a":3}]')[0].a}catch(c){}Qe=aj&&!yu("[00]")&&!yu('"\u0007"')&&!yu('"\\0"')&&!yu('"\\v"')}finally{af=a}}};_.of=function(a){if(-1===af)return!1;SE();return(Qe?yu:me)(a)};
_.mf=function(a){if(-1!==af)return SE(),aj?_.D.JSON.stringify.call(_.D.JSON,a):qt(a)};qy=!Date.prototype.toISOString||"function"!==typeof Date.prototype.toISOString||"1970-01-01T00:00:00.000Z"!==(new Date(0)).toISOString();
QA=function(){var a=Date.prototype.getUTCFullYear.call(this);return[0>a?"-"+String(1E6-a).substr(1):9999>=a?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1), "Z"].join("")};Date.prototype.toISOString=qy?QA:Date.prototype.toISOString;

_.Mu("gadgets.json.stringify",_.mf);_.Mu("gadgets.json.parse",_.of);
_.e(_.ta.location.href,"rpctoken")&&_.La(_.ua,"unload",function(){});
var Qb;_.Ma=function(){var a=_.ua.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Wa=function(a){if(_.Ma())a();else{var c=!1,f=function(){if(!c)return c=!0,a.apply(this,arguments)};_.ta.addEventListener?(_.ta.addEventListener("load",f,!1),_.ta.addEventListener("DOMContentLoaded",f,!1)):_.ta.attachEvent&&(_.ta.attachEvent("onreadystatechange",function(){_.Ma()&&f.apply(this,arguments)}),_.ta.attachEvent("onload",f))}};Qb=Qb||{};Qb.Km=null; Qb.bm=null;Qb.FM=null;Qb.frameElement=null;
Qb=Qb||{};
Qb.Lj||(Qb.Lj=function(){function a(a,c,f){"undefined"!=typeof window.addEventListener?window.addEventListener(a,c,f):"undefined"!=typeof window.attachEvent&&window.attachEvent("on"+a,c);"message"===a&&(window.___jsl=window.___jsl||{},a=window.___jsl,a.RPMQ=a.RPMQ||[],a.RPMQ.push(c))}function c(a){var c=_.of(a.data);if(c&&c.f){(0,_.Fc)("gadgets.rpc.receive("+window.name+"): "+a.data);var g=_.T.$d(c.f);h&&("undefined"!==typeof a.origin?a.origin!==g:a.domain!==/^.+:\/\/([^:]+).*/.exec(g)[1])?_.sa("Invalid rpc message origin. "+
g+" vs "+(a.origin||"")):f(c,a.origin)}}var f,g,h=!0;return{Kk:function(){return"wpm"},jga:function(){return!0},kc:function(l,n){_.Pb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(h=!1)});f=l;g=n;a("message",c,!1);g("..",!0);return!0},sf:function(a){g(a,!0);return!0},call:function(a,c,f){var g=_.T.$d(a),h=_.T.dk(a);g?window.setTimeout(function(){var a=_.mf(f);(0,_.Fc)("gadgets.rpc.send("+window.name+"): "+a);h.postMessage(a,g)},0):".."!=a&&_.sa("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.T&&_.T||(_.T=window.gadgets.rpc,_.T.config=_.T.config,_.T.register=_.T.register,_.T.unregister=_.T.unregister,_.T.Am=_.T.registerDefault,_.T.aB=_.T.unregisterDefault,_.T.Fk=_.T.forceParentVerifiable,_.T.call=_.T.call,_.T.Rk=_.T.getRelayUrl,_.T.Xg=_.T.setRelayUrl,_.T.Wg=_.T.setAuthToken,_.T.tf=_.T.setupReceiver,_.T.Wd=_.T.getAuthToken,_.T.mj=_.T.removeReceiver,_.T.Qk=_.T.getRelayChannel,_.T.ym=_.T.receive,_.T.zm=_.T.receiveSameDomain,_.T.Pq=
_.T.getOrigin,_.T.$d=_.T.getTargetOrigin,_.T.dk=_.T._getTargetWin,_.T.Uo=_.T._parseSiblingId);else{_.T=function(){function a(a,c){if(!Ta[a]){var f=fc;c||(f=te);Ta[a]=f;c=Ya[a]||[];for(var g=0;g<c.length;++g){var h=c[g];h.t=ka[a];f.call(a,h.f,h)}Ya[a]=[]}}function c(){function a(){Go=!0}Ho||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),Ho=!0)}function f(a,f,g,h,l){ka[f]&&ka[f]===g||(_.sa("Invalid gadgets.rpc token. "+
ka[f]+" vs "+g),ok(f,2));l.onunload=function(){ja[f]&&!Go&&(ok(f,1),_.T.mj(f))};c();h=_.of((0,window.decodeURIComponent)(h))}function g(c,f){if(c&&"string"===typeof c.s&&"string"===typeof c.f&&c.a instanceof Array)if(ka[c.f]&&ka[c.f]!==c.t&&(_.sa("Invalid gadgets.rpc token. "+ka[c.f]+" vs "+c.t),ok(c.f,2)),"__ack"===c.s)window.setTimeout(function(){a(c.f,!0)},0);else{c.c&&(c.callback=function(a){_.T.call(c.f,(c.g?"legacy__":"")+"__cb",null,c.c,a)});if(f){var g=h(f);c.origin=f;var l=c.r;try{var n=
h(l)}catch($B){}l&&n==g||(l=f);c.referer=l}f=(E[c.s]||E[""]).apply(c,c.a);c.c&&"undefined"!==typeof f&&_.T.call(c.f,"__cb",null,c.c,f)}}function h(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==
a&&"android-app"!==a&&"chrome-search"!==a)throw Error("Pa");f="";var g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1);c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f}function l(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):null}}return null}function n(a){if("undefined"===typeof a||".."===a)return window.parent;var c=l(a);if(c)return window.top.frames[c.id];a=String(a);return(c=window.frames[a])?
c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:null}function q(a,c){if(!0!==ja[a]){"undefined"===typeof ja[a]&&(ja[a]=0);var f=n(a);".."!==a&&null==f||!0!==fc.sf(a,c)?!0!==ja[a]&&10>ja[a]++?window.setTimeout(function(){q(a,c)},500):(Ta[a]=te,ja[a]=!0):ja[a]=!0}}function t(a){(a=K[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function v(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));K[a]=c;"undefined"!==typeof f&&(U[a]=!!f)}function w(a,c){c=c||"";ka[a]=String(c);q(a,c)}function A(a){a=(a.passReferrer||"").split(":",2);If=a[0]||"none";wh=a[1]||"origin"}function F(c){"true"===String(c.useLegacyProtocol)&&(fc=Qb.FM||te,fc.kc(g,a))}function z(a,c){function f(f){f=f&&f.rpc||{};A(f);var g=f.parentRelayUrl||
"";g=h(rw.parent||c)+g;v("..",g,"true"===String(f.useLegacyProtocol));F(f);w("..",a)}!rw.parent&&c?f({}):_.Pb.register("rpc",null,f)}function I(a,c,f){if(".."===a)z(f||rw.rpctoken||rw.ifpctok||"",c);else a:{var g=null;if("/"!=a.charAt(0)){if(!_.R)break a;g=window.document.getElementById(a);if(!g)throw Error("h`"+a);}g=g&&g.src;c=c||_.T.Pq(g);v(a,c);c=_.R.Qc(g);w(a,f||c.rpctoken)}}var E={},K={},U={},ka={},S=0,Ca={},ja={},rw={},Ta={},Ya={},If=null,wh=null,nk=window.top!==window.self,Yw=window.name,
ok=function(){},pk=window.console,Io=pk&&pk.log&&function(a){pk.log(a)}||function(){},te=function(){function a(a){return function(){Io(a+": call ignored")}}return{Kk:function(){return"noop"},jga:function(){return!0},kc:a("init"),sf:a("setup"),call:a("call")}}();_.R&&(rw=_.R.Qc());var Go=!1,Ho=!1,fc=function(){if("rmr"==rw.rpctx)return Qb.Km;var a="function"===typeof window.postMessage?Qb.Lj:"object"===typeof window.postMessage?Qb.Lj:window.ActiveXObject?Qb.bm?Qb.bm:Qb.FM:0<window.navigator.userAgent.indexOf("WebKit")?
Qb.Km:"Gecko"===window.navigator.product?Qb.frameElement:Qb.FM;a||(a=te);return a}();E[""]=function(){Io("Unknown RPC service: "+this.s)};E.__cb=function(a,c){var f=Ca[a];f&&(delete Ca[a],f.call(this,c))};return{config:function(a){"function"===typeof a.Mm&&(ok=a.Mm)},register:function(a,c){if("__cb"===a||"__ack"===a)throw Error("i");if(""===a)throw Error("j");E[a]=c},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("k");if(""===a)throw Error("l");delete E[a]},Am:function(a){E[""]=a},
aB:function(){delete E[""]},Fk:function(){},call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=Yw:"/"==a.charAt(0)&&(h=_.T.Pq(window.location.href),h="/"+Yw+(h?"|"+h:""));++S;f&&(Ca[S]=f);var n={s:c,f:h,c:f?S:0,a:Array.prototype.slice.call(arguments,3),t:ka[a],l:!!U[a]};a:if("bidir"===If||"c2p"===If&&".."===a||"p2c"===If&&".."!==a){var q=window.location.href;var t="?";if("query"===wh)t="#";else if("hash"===wh)break a;t=q.lastIndexOf(t);t=-1===t?q.length:t;q=q.substring(0,t)}else q=null;q&&(n.r=
q);if(".."===a||null!=l(a)||window.document.getElementById(a))(q=Ta[a])||null===l(a)||(q=fc),0===c.indexOf("legacy__")&&(q=fc,n.s=c.substring(8),n.c=n.c?n.c:S),n.g=!0,n.r=h,q?(U[a]&&(q=Qb.FM),!1===q.call(a,h,n)&&(Ta[a]=te,fc.call(a,h,n))):Ya[a]?Ya[a].push(n):Ya[a]=[n]},Rk:t,Xg:v,Wg:w,tf:I,Wd:function(a){return ka[a]},mj:function(a){delete K[a];delete U[a];delete ka[a];delete ja[a];delete Ta[a]},Qk:function(){return fc.Kk()},ym:function(a,c){4<a.length?fc.Vo(a,g):f.apply(null,a.concat(c))},zm:function(a){a.a=
Array.prototype.slice.call(a.a);window.setTimeout(function(){g(a)},0)},Pq:h,$d:function(a){var c=null,f=t(a);f?c=f:(f=l(a))?c=f.origin:".."==a?c=rw.parent:(a=window.document.getElementById(a))&&"iframe"===a.tagName.toLowerCase()&&(c=a.src);return h(c)},kc:function(){!1===fc.kc(g,a)&&(fc=te);nk?I(".."):_.Pb.register("rpc",null,function(a){a=a.rpc||{};A(a);F(a)})},dk:n,Uo:l,Iia:"__ack",lh:Yw||"..",Pia:0,Oia:1,Nia:2}}();_.T.kc()};
_.T.config({Mm:function(a){throw Error("m`"+a);}});_.Fc=_.ke;_.Mu("gadgets.rpc.config",_.T.config);_.Mu("gadgets.rpc.register",_.T.register);_.Mu("gadgets.rpc.unregister",_.T.unregister);_.Mu("gadgets.rpc.registerDefault",_.T.Am);_.Mu("gadgets.rpc.unregisterDefault",_.T.aB);_.Mu("gadgets.rpc.forceParentVerifiable",_.T.Fk);_.Mu("gadgets.rpc.call",_.T.call);_.Mu("gadgets.rpc.getRelayUrl",_.T.Rk);_.Mu("gadgets.rpc.setRelayUrl",_.T.Xg);_.Mu("gadgets.rpc.setAuthToken",_.T.Wg);_.Mu("gadgets.rpc.setupReceiver",_.T.tf);_.Mu("gadgets.rpc.getAuthToken",_.T.Wd); _.Mu("gadgets.rpc.removeReceiver",_.T.mj);_.Mu("gadgets.rpc.getRelayChannel",_.T.Qk);_.Mu("gadgets.rpc.receive",_.T.ym);_.Mu("gadgets.rpc.receiveSameDomain",_.T.zm);_.Mu("gadgets.rpc.getOrigin",_.T.Pq);_.Mu("gadgets.rpc.getTargetOrigin",_.T.$d);

_.R=_.R||{};_.R.Ee=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):_.Lb("cannot attachBrowserEvent: "+c)};_.R.Vr=function(a){var c=window;c.removeEventListener?c.removeEventListener("mousemove",a,!1):c.detachEvent?c.detachEvent("onmousemove",a):_.Lb("cannot removeBrowserEvent: mousemove")};

_.Tb=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=v=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)a=c[f-3]^c[f-8]^c[f-14]^c[f-16],c[f]=(a<<1|a>>>31)&4294967295;a=h[0];var g=h[1],l=h[2],q=h[3],t=h[4];for(f=0;80>f;f++){if(40>f)if(20>f){var v=q^g&(l^q);var w=1518500249}else v=g^l^q,w=1859775393;else 60>f?(v=g&l|q&(g|l),w=2400959708):(v=g^l^q,w=3395469782);v=((a<<5|a>>>27)&4294967295)+
v+t+w+c[f]&4294967295;t=q;q=l;l=(g<<30|g>>>2)&4294967295;g=a;a=v}h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==v)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(l[v++]=a[g++],w++,64==v)for(v=0,c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}
function g(){var a=[],g=8*w;56>v?f(q,56-v):f(q,64-(v-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var t=24;0<=t;t-=8)a[g++]=h[n]>>t&255;return a}for(var h=[],l=[],n=[],q=[128],t=1;64>t;++t)q[t]=0;var v,w;a();return{reset:a,update:f,digest:g,Of:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};
_.Vb=function(){function a(a){var c=_.Tb();c.update(a);return c.Of()}var c=window.crypto;if(c&&"function"==typeof c.getRandomValues)return function(){var a=new window.Uint32Array(1);c.getRandomValues(a);return Number("0."+a[0])};var f=_.P("random/maxObserveMousemove");null==f&&(f=-1);var g=0,h=Math.random(),l=1,n=1E6*(window.screen.width*window.screen.width+window.screen.height),q=function(a){a=a||window.event;var c=a.screenX+a.clientX<<16;c+=a.screenY+a.clientY;c*=(new Date).getTime()%1E6;l=l*c%
n;0<f&&++g==f&&_.R.Vr(q)};0!=f&&_.R.Ee(window,"mousemove",q,!1);var t=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+h);return function(){var c=l;c+=(0,window.parseInt)(t.substr(0,20),16);t=a(t);return c/(n+Math.pow(16,20))}}();
_.Mu("shindig.random",_.Vb);
});
// Google Inc.
